### ISSUE TITLE
'assist

### ISSUE THREAD

**Issue by 0xWerz** [7xRone/show-dowbload-upload-files#1]
maybe you need to add requirements with a .txt extension in the file **show-dowbload-upload-files-main** to download all libraries you used with one line on the terminal ;
`pip install -r requirements.txt`

**Comment by hizawye** [comment]
Yeah yeah i got you but you should just install the Dropbox sdk ,so i think it does not need all that.
Anyway i will add try except to install it automatically.
Thanks.

**Comment by razewerz** [comment]
[Uploading edited .rar…]()

**Comment by hizawye** [comment]
Done.
